{% set name = "testfixtures" %}
{% set version = "9.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 517e9cf353942723533ae1100ca45dd27fe0785c3ad2765075f5cb1cbce01482

build:
  skip: true # [py<311]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

# django package in not available now, skip tests for it
# 
# AssertionError: Expected AssertionError('\n<SequenceComparison(ordered=True, partial=False)(failed)>\nsame:\n[]\n\nexpected:
# \n[<C:builtins.DeprecationWarning>]\n\nactual:\n[]\n</SequenceComparison(ordered=True, partial=False)> (expected) != [] (actual)'), None raised!
{% set skip_tests = [
  "--ignore=testfixtures/tests/test_django", 
  '--deselect=testfixtures/tests/test_shouldwarn.py::ShouldWarnTests::test_filter_missing',
  '--deselect=testfixtures/tests/test_shouldwarn.py::ShouldWarnTests::test_filter_present',
]%}
# AssertionError:
# -+++ Reading from "C:\Users\TA9AC1~1\AppData\Local\Temp\tmpblvwk_5c/foo":
# ++++ Reading from "C:\Users\TA9AC1~1\AppData\Local\Temp\tmpblvwk_5c\foo":
{% set skip_tests = skip_tests + ["--deselect=testfixtures/tests/test_sybil.py::TestFileParser::test_evaluate_read_difference"] %}  # [win]

test:
  source_files:
    - testfixtures
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django
  requires:
    - pip
    - sybil
    - twisted
    - pytest>=7.1
  commands:
    - pip check
    - pytest -v testfixtures/tests {{ skip_tests | join(' ')}}

about:
  home: https://testfixtures.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A collection of helpers and mock objects for unit tests and doc tests.
  description: |
    Testfixtures is a collection of helpers and mock objects that are useful when writing automated tests in Python.
  doc_url: https://testfixtures.readthedocs.io
  dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
