{% set version = "5.3.1" %}
{% set sha256 = "670ade9410b7132278209e6a2e893caf098b040c4ba4d5ea848367a9c5588728" %}

package:
    name: testfixtures
    version: {{ version }}

source:
    fn: testfixtures-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    host:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - testfixtures
        - testfixtures.tests
        - testfixtures.tests.test_django

about:
    home: http://pythonhosted.org/testfixtures/
    license: MIT
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
    doc_url: https://testfixtures.readthedocs.io/en/latest/
    dev_url: https://github.com/Simplistix/testfixtures

extra:
    recipe-maintainers:
        - ChrisBarker-NOAA
        - JamesMakela-NOAA
