{% set version = "9.1.0" %}

package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: 517e9cf353942723533ae1100ca45dd27fe0785c3ad2765075f5cb1cbce01482

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<311]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://testfixtures.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A collection of helpers and mock objects for unit tests and doc tests.
  doc_url: https://testfixtures.readthedocs.io
  dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
